import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import PageHeader from '../components/PageHeader'
import ExperienceYears from '../components/ExperienceYears'
import TextBody from '../components/TextBody'
import Footer from '../components/Footer'

const Home: NextPage = () => {
  return (
    <div className='min-h-screen flex flex-col bg-brand-white'>
      <Head>
        <title>Andrew Sleigh Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='flex flex-1 flex-col container mx-auto my-10 '>
        <PageHeader pageTitle='Hello :)' />
        <article className='pb-4 pt-10'>
          <TextBody>My name is Andrew</TextBody>
          <TextBody>I’m a web developer of <ExperienceYears /></TextBody>
          <TextBody>I like to code, hack and adventure life away</TextBody>
          <TextBody>Current Location: <span className='underline decoration-brand-pink underline-offset-4'>United Kingdom</span></TextBody>
        </article>
      </main>

      <Footer />
    </div>
  )
}

export default Home
