import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import PageHeader from '../components/PageHeader'
import ExperienceYears from '../components/ExperienceYears'
import KeySkillList from '../components/KeySkillList'
import TextBody from '../components/TextBody'
import Footer from '../components/Footer'
import Button from '../components/Button'
import PictureOfMe from '../components/PictureOfMe'
import MobileMenu from '../components/MobileMenu'

const Home: NextPage = () => {
  return (
    <div className='min-h-screen flex flex-col'>
      <Head>
        <title>Andrew Sleigh UI Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isHomePage={true} />
      <div className='flex flex-1 flex-col md:mb-48 mb-12'>
        <div className='gradient-bg'>
          <main className='container mx-auto pt-28 pb-10 px-5 md:px-0'>
            <div className='flex flex-col md:grid md:grid-cols-12'>
              <div className='md:col-start-1 md:col-end-5'>
                <div>
                  <PageHeader twClass='text-white' pageTitle='Hello :)' />
                  <p className='text-xl py-8 md:py-16 text-white'>My name is Andrew <br /><br />I develop Websites and UI’s <br /><br />I like to code, hack and adventure life away</p>
                  <p className="md:text-5xl text-3xl pt-2 pb-1 text-white"><ExperienceYears /></p>
                  <span className='block text-xl pb-1 text-white'>experience</span>
                  <span className='text-xl text-white'>current location</span>
                  <p className='md:text-5xl text-3xl text-white'>Newquay,UK</p>
                </div>

              </div>
                <PictureOfMe />
            </div>
            <div className="md:pt-1 pt-8 text-right md:text-left">
              <Button isLink={true} hasArrow={false} classes={`text-white px-5 py-6 rounded-main text-xl bg-primary hover:bg-primary-darken`} text={`Heres my CV`} href="/andrew-sleigh-cv-2022.pdf" arrowColor="text-white" />
            </div>
          </main>
        </div>

        <div className='mt-10 container mx-auto px-5 md:px-0'>
          <KeySkillList />
        </div>
      </div>

      <Footer />
      <MobileMenu />
    </div>
  )
}

export default Home
